[package]
name = "snakegame"
version = "0.1.0"
authors = ["Volodymyr Shamray <shamray@outlook.com>"]
edition = "2018"

[dependencies]
good-web-game = "0.5"
rand = "0.8"

[profile.dev]
opt-level = 0
debug = 2
debug-assertions = true